### ISSUE TITLE
报告一个bug

### ISSUE THREAD

**Issue by DamonDBT** [HanbGao/EchartCommonLib#1]
` public static string ToJson(this object obj)
        {
            //var jSetting = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Include };
            var jSetting = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
            var json = JsonConvert.SerializeObject(obj, (Newtonsoft.Json.Formatting)Formatting.Indented, jSetting);
            var data = JsonConvert.DeserializeObject(json, typeof(object), jSetting);
            var timeConverter = new Newtonsoft.Json.Converters.IsoDateTimeConverter { DateTimeFormat = "yyyy'-'MM'-'dd hh:mm" };
            json = JsonConvert.SerializeObject(data, (Newtonsoft.Json.Formatting)Formatting.Indented, timeConverter);
            return json;
        }
`

这段代码中要注意，原文件中是NullValueHandling.Include，在json时对null的也转换了，如果这样会遇到echart无法显示的问题，我修改为var jSetting = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };  不处理值为null的属性，可以显示了。
另外，echart中，用''和“”，没有影响。

**Comment by xhanb** [comment]
已修复
